name: animated_switcher_wrapper

description: "Basic wrapper for AnimatedSwitcher to provide a some custom animations."

version: 0.0.1

repository: https://github.com/ericwimp8/animated_switcher_wrapper

homepage: https://github.com/ericwimp8/animated_switcher_wrapper

issue_tracker: https://github.com/ericwimp8/animated_switcher_wrapper/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  very_good_analysis: ^5.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
